name: Create Release
on:
  workflow_call:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
        with:
          name: $key/${{github.event.inputs.version}}
        env:
          GH_TOKEN: ${{ github.token }}
