name: Generate and Publish SDK
on:
  workflow_dispatch:
    inputs:
      id:
        description: 'run identifier'
        required: false
      version:
        description: 'generated sdk version'
        required: true
        default: ''
      name:
        description: 'generated sdk name'
        required: true
      fileAsBase64:
        description: 'generated sdk file as base64 encoded'
        required: true
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
  generate_sdk:
    uses: ./.github/workflows/generate-sdk.yaml
    needs: [ id ]
    with:
      version: ${{ github.event.inputs.version }}
      name: ${{ github.event.inputs.name }}
      fileAsBase64: ${{ github.event.inputs.fileAsBase64 }}
  commit_sdk:
    needs: [ generate_sdk ]
    uses: ./.github/workflows/commit-sdk.yaml
  publish_sdk:
    needs: [ generate_sdk ]
    uses: ./.github/workflows/publish-sdk.yaml
    secrets: inherit 
  
